### ISSUE TITLE
Delete button not working onclick

### ISSUE THREAD

**Issue by Titus-Kiplagat** [dvcorreia1984/Awesome-books-with-ES6#2]
**Description:**
- The delete button in the application is not functioning correctly when clicked. It should trigger the deletion of the specified item but fails to do so.

**Expected behavior:**
- Upon clicking the delete button, the application should successfully delete the corresponding item and update the interface accordingly.

**Possible solution:**
- One possible solution could be to investigate the event handling for the delete button and ensure that the corresponding delete functionality is triggered correctly. 
- Consider modifying the on-click handler function for the delete button to receive the index of the corresponding item. This index information can be passed as an argument to the function (removeBooks function) or retrieved through other means, such as data attributes on the delete button element or by using a closure to preserve the index value.

**Comment by dvcorreia1984** [comment]
Fixed these issues!.
